# install-task.ps1 - register Farewatch as a twice-daily Windows scheduled task.
#
# Why a local task rather than only GitHub Actions: Google serves datacenter IPs
# a bot challenge often enough that a cloud-only collector ends up with holes in
# the series. Your machine has a residential IP, so it gets real answers. The
# task runs whether or not you are logged in at that moment, and catches up if
# the machine was asleep at the scheduled time.
#
#   powershell -ExecutionPolicy Bypass -File install-task.ps1
#   powershell -ExecutionPolicy Bypass -File install-task.ps1 -Remove
#
# Check on it later:
#   Get-ScheduledTask Farewatch | Get-ScheduledTaskInfo
#   Get-Content farewatch.log -Tail 40

param(
    [switch]$Remove,
    [string]$TaskName = "Farewatch"
)

$ErrorActionPreference = "Stop"

if ($Remove) {
    try {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Removed scheduled task '$TaskName'."
    } catch {
        Write-Host "No scheduled task named '$TaskName' to remove."
    }
    return
}

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$python = (Get-Command python).Source
if (-not $python) { throw "python not found on PATH." }

# pythonw.exe runs with no console window, so a scheduled run never flashes a
# black box over whatever you are doing.
$pythonw = Join-Path (Split-Path -Parent $python) "pythonw.exe"
if (Test-Path $pythonw) { $python = $pythonw }

Write-Host "Python : $python"
Write-Host "Folder : $here"

# Task Scheduler hands the argument string to cmd.exe, and cmd has a famously
# bad habit: when the string after /c starts with a quote it strips the first
# and last quote characters, which mangles both the exe path and the redirect
# target. Rather than fight that, generate a one-line batch file and point the
# task at it -- .bat quoting is predictable, and you can double-click it to
# test by hand.
$runner = Join-Path $here "run.bat"
@"
@echo off
rem Generated by install-task.ps1 -- re-run that script to regenerate.
cd /d "%~dp0"
"$python" farewatch.py --notify >> "%~dp0farewatch.log" 2>&1
"@ | Set-Content -Path $runner -Encoding ascii

Write-Host "Runner : $runner"

$action = New-ScheduledTaskAction -Execute $runner -WorkingDirectory $here

$triggers = @(
    (New-ScheduledTaskTrigger -Daily -At 8:10am),
    (New-ScheduledTaskTrigger -Daily -At 8:10pm)
)

$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -DontStopIfGoingOnBatteries `
    -AllowStartIfOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 30) `
    -MultipleInstances IgnoreNew `
    -Hidden

# Run as you, only when you are logged on. That keeps it out of SYSTEM's
# profile, so it uses your PATH and your installed packages -- and it never
# needs your password stored anywhere.
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $triggers `
    -Settings $settings -Principal $principal -Force `
    -Description "Record MCI-UVF fares twice daily and email only when they move." | Out-Null

Write-Host ""
Write-Host "Registered '$TaskName' - runs 8:10am and 8:10pm daily."
Write-Host "Missed runs (laptop asleep) fire as soon as it wakes."
Write-Host ""
Write-Host "Run it once now to confirm:"
Write-Host "  Start-ScheduledTask -TaskName $TaskName"
Write-Host "  Get-Content `"$here\farewatch.log`" -Tail 40"
